### ISSUE TITLE
Is `-usehd` a flag or an option?

### ISSUE THREAD

**Issue by coolaj86** [dashpay/docs-core#33]
Docs here show that `-usehd` is a boolean flag:
https://docs.dash.org/projects/core/en/stable/docs/dashcore/wallet-arguments-and-commands-dashd.html

Docs here show that `-usehd=1` is an option (meaning a flag that accepts an argument):
https://docs.dash.org/en/stable/docs/user/wallets/dashcore/advanced.html

Or is it both?

One (or both) of them needs to be updated.

**Comment by thephez** [comment]
The former is correct. It is a direct copy from `dashd --help`. I just noticed the latter yesterday while updating that page. It's in the process of being updated via an [open PR](https://github.com/dashpay/docs/pull/277).
