### ISSUE TITLE
No mention of instantsend status for `getaddressutxos`

### ISSUE THREAD

**Issue by coolaj86** [dashpay/docs-core#40]
Some of our tools respect `instantsend` and others do not (I've noticed this when getting balances through insight.dash.org, which I assume calls `getaddressbalance` under the hood).

I believe that `getaddressutxos` from the dashcore RPCs _will_ respect `instantsend`, but it's not mentioned in the documentation by "instant send", "instantsend", "chain lock", or "chainlock":
https://docs.dash.org/projects/core/en/stable/docs/api/remote-procedure-calls-address-index.html#getaddressbalance

We should have documented reference of whether or not each function call does or doesn't support instant send so that we don't have to compare addresses empirically at time of transfer to find out.

**Comment by thephez** [comment]
I checked with @UdjinM6 about this. From the Core / RPC side, any RPCs that support IS/CL include the `instantlock` / `chainlock` fields so the absence of them indicates no support for whatever reason. For example, the data for `-addressindex` related RPCs is only updated on block connects/disconnects so it doesn't support them.
